webserver:
  restart: always
  image: jorjoh/varden
  ports:
    - "80:80"
  links:
   - mysqldb

mysqldb:
 restart: always
 image: mysql
 environment:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: varden
 ports:
   - 3306:3306
 volumes:
   - ./dbdump:/docker-entrypoint-initdb.d
