<?php include('searchfield.php'); ?>
<br>
<div class="row">
    <div class="col-12">
        <div style="width: 100%; background: #FFF;">
            <br>
            <br>
            <div style="width: 60%; height: 100px; text-align: center; margin: 0 auto; background: #CCC;"><br><br>Annonse her som vises uansett om du har adblock eller ikke</div>
            <br>
            <br>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <div style="display: inline-block; width: 50px; height: 50px; background: #FF0000;"></div>
            <br>
        </div>
    </div>
</div>